name: lisha
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  flutter_native_splash: ^2.4.1
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.6
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.0.0
  tab_container: ^3.5.3
  flutter_swipe_action_cell: ^3.1.4
  emoji_picker_flutter: ^3.0.0
  supabase_flutter: ^2.6.0
  shared_preferences: ^2.3.2
  gradient_borders: ^1.0.1
  image_picker: ^1.1.2
  styled_divider: ^1.0.5
  app_links: ^6.3.2
  flutter_calendar_carousel: ^2.4.4
  calendar_date_picker2: ^1.1.7
  fluttertoast: ^8.2.8
  dotted_border: ^2.1.0
  dotted_line: ^3.2.3
  avatar_stack: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  logger: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/dummies/
    - .env

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800
    - family: Lufga
      fonts:
        - asset: fonts/LufgaRegular.ttf
          weight: 400
        - asset: fonts/LufgaSemiBold.ttf
          weight: 600
        - asset: fonts/LufgaBold.ttf
          weight: 700

flutter_native_splash:
  color: "#2E323B"

  android_12:
    color: "#2E323B"
